import { Category, Exercise } from './schema';

export const categories: Category[] = [
  { id: 'chest', name: 'Chest' },
  { id: 'back', name: 'Back' },
  { id: 'shoulders', name: 'Shoulders' },
  { id: 'triceps', name: 'Triceps' },
  { id: 'biceps', name: 'Biceps' },
  { id: 'legs', name: 'Legs' },
  { id: 'core', name: 'Core' },
  { id: 'cardio', name: 'Cardio' },
  { id: 'full-body', name: 'Full Body' },
];

export const exercisePool: Exercise[] = [
  // Chest
  { id: 'bench-press', name: 'Bench Press', category: 'Chest', is_custom: false },
  { id: 'incline-bench-press', name: 'Incline Bench Press', category: 'Chest', is_custom: false },
  { id: 'decline-bench-press', name: 'Decline Bench Press', category: 'Chest', is_custom: false },
  { id: 'dumbbell-press', name: 'Dumbbell Press', category: 'Chest', is_custom: false },
  { id: 'incline-dumbbell-press', name: 'Incline Dumbbell Press', category: 'Chest', is_custom: false },
  { id: 'dumbbell-flyes', name: 'Dumbbell Flyes', category: 'Chest', is_custom: false },
  { id: 'incline-flyes', name: 'Incline Flyes', category: 'Chest', is_custom: false },
  { id: 'push-ups', name: 'Push-ups', category: 'Chest', is_custom: false },
  { id: 'diamond-push-ups', name: 'Diamond Push-ups', category: 'Chest', is_custom: false },
  { id: 'dips', name: 'Dips', category: 'Chest', is_custom: false },
  { id: 'cable-flyes', name: 'Cable Flyes', category: 'Chest', is_custom: false },
  { id: 'pec-deck', name: 'Pec Deck', category: 'Chest', is_custom: false },

  // Back
  { id: 'deadlift', name: 'Deadlift', category: 'Back', is_custom: false },
  { id: 'barbell-rows', name: 'Barbell Rows', category: 'Back', is_custom: false },
  { id: 'pull-ups', name: 'Pull-ups', category: 'Back', is_custom: false },
  { id: 'chin-ups', name: 'Chin-ups', category: 'Back', is_custom: false },
  { id: 'lat-pulldown', name: 'Lat Pulldown', category: 'Back', is_custom: false },
  { id: 'seated-cable-rows', name: 'Seated Cable Rows', category: 'Back', is_custom: false },
  { id: 't-bar-rows', name: 'T-Bar Rows', category: 'Back', is_custom: false },
  { id: 'one-arm-dumbbell-rows', name: 'One-Arm Dumbbell Rows', category: 'Back', is_custom: false },
  { id: 'face-pulls', name: 'Face Pulls', category: 'Back', is_custom: false },
  { id: 'reverse-flyes', name: 'Reverse Flyes', category: 'Back', is_custom: false },
  { id: 'shrugs', name: 'Shrugs', category: 'Back', is_custom: false },
  { id: 'hyperextensions', name: 'Hyperextensions', category: 'Back', is_custom: false },

  // Shoulders
  { id: 'overhead-press', name: 'Overhead Press', category: 'Shoulders', is_custom: false },
  { id: 'dumbbell-press', name: 'Dumbbell Shoulder Press', category: 'Shoulders', is_custom: false },
  { id: 'lateral-raises', name: 'Lateral Raises', category: 'Shoulders', is_custom: false },
  { id: 'front-raises', name: 'Front Raises', category: 'Shoulders', is_custom: false },
  { id: 'rear-delt-flyes', name: 'Rear Delt Flyes', category: 'Shoulders', is_custom: false },
  { id: 'arnold-press', name: 'Arnold Press', category: 'Shoulders', is_custom: false },
  { id: 'upright-rows', name: 'Upright Rows', category: 'Shoulders', is_custom: false },
  { id: 'pike-push-ups', name: 'Pike Push-ups', category: 'Shoulders', is_custom: false },
  { id: 'handstand-push-ups', name: 'Handstand Push-ups', category: 'Shoulders', is_custom: false },

  // Triceps
  { id: 'close-grip-bench-press', name: 'Close-Grip Bench Press', category: 'Triceps', is_custom: false },
  { id: 'tricep-dips', name: 'Tricep Dips', category: 'Triceps', is_custom: false },
  { id: 'overhead-tricep-extension', name: 'Overhead Tricep Extension', category: 'Triceps', is_custom: false },
  { id: 'tricep-pushdowns', name: 'Tricep Pushdowns', category: 'Triceps', is_custom: false },
  { id: 'skull-crushers', name: 'Skull Crushers', category: 'Triceps', is_custom: false },
  { id: 'diamond-push-ups', name: 'Diamond Push-ups', category: 'Triceps', is_custom: false },
  { id: 'tricep-kickbacks', name: 'Tricep Kickbacks', category: 'Triceps', is_custom: false },
  { id: 'overhead-dumbbell-extension', name: 'Overhead Dumbbell Extension', category: 'Triceps', is_custom: false },
  { id: 'cable-overhead-extension', name: 'Cable Overhead Extension', category: 'Triceps', is_custom: false },
  { id: 'bench-dips', name: 'Bench Dips', category: 'Triceps', is_custom: false },
  { id: 'rope-pushdowns', name: 'Rope Pushdowns', category: 'Triceps', is_custom: false },
  { id: 'lying-tricep-extension', name: 'Lying Tricep Extension', category: 'Triceps', is_custom: false },

  // Biceps
  { id: 'barbell-curls', name: 'Barbell Curls', category: 'Biceps', is_custom: false },
  { id: 'dumbbell-curls', name: 'Dumbbell Curls', category: 'Biceps', is_custom: false },
  { id: 'hammer-curls', name: 'Hammer Curls', category: 'Biceps', is_custom: false },
  { id: 'preacher-curls', name: 'Preacher Curls', category: 'Biceps', is_custom: false },
  { id: 'concentration-curls', name: 'Concentration Curls', category: 'Biceps', is_custom: false },
  { id: 'cable-curls', name: 'Cable Curls', category: 'Biceps', is_custom: false },
  { id: 'reverse-curls', name: 'Reverse Curls', category: 'Biceps', is_custom: false },
  { id: 'spider-curls', name: 'Spider Curls', category: 'Biceps', is_custom: false },
  { id: '21s', name: '21s', category: 'Biceps', is_custom: false },
  { id: 'incline-dumbbell-curls', name: 'Incline Dumbbell Curls', category: 'Biceps', is_custom: false },
  { id: 'cable-hammer-curls', name: 'Cable Hammer Curls', category: 'Biceps', is_custom: false },
  { id: 'ez-bar-curls', name: 'EZ-Bar Curls', category: 'Biceps', is_custom: false },

  // Legs
  { id: 'squats', name: 'Squats', category: 'Legs', is_custom: false },
  { id: 'front-squats', name: 'Front Squats', category: 'Legs', is_custom: false },
  { id: 'goblet-squats', name: 'Goblet Squats', category: 'Legs', is_custom: false },
  { id: 'bulgarian-split-squats', name: 'Bulgarian Split Squats', category: 'Legs', is_custom: false },
  { id: 'lunges', name: 'Lunges', category: 'Legs', is_custom: false },
  { id: 'walking-lunges', name: 'Walking Lunges', category: 'Legs', is_custom: false },
  { id: 'leg-press', name: 'Leg Press', category: 'Legs', is_custom: false },
  { id: 'leg-curls', name: 'Leg Curls', category: 'Legs', is_custom: false },
  { id: 'leg-extensions', name: 'Leg Extensions', category: 'Legs', is_custom: false },
  { id: 'romanian-deadlifts', name: 'Romanian Deadlifts', category: 'Legs', is_custom: false },
  { id: 'stiff-leg-deadlifts', name: 'Stiff-Leg Deadlifts', category: 'Legs', is_custom: false },
  { id: 'calf-raises', name: 'Calf Raises', category: 'Legs', is_custom: false },
  { id: 'wall-sits', name: 'Wall Sits', category: 'Legs', is_custom: false },
  { id: 'jump-squats', name: 'Jump Squats', category: 'Legs', is_custom: false },

  // Core
  { id: 'plank', name: 'Plank', category: 'Core', is_custom: false },
  { id: 'side-plank', name: 'Side Plank', category: 'Core', is_custom: false },
  { id: 'crunches', name: 'Crunches', category: 'Core', is_custom: false },
  { id: 'sit-ups', name: 'Sit-ups', category: 'Core', is_custom: false },
  { id: 'russian-twists', name: 'Russian Twists', category: 'Core', is_custom: false },
  { id: 'mountain-climbers', name: 'Mountain Climbers', category: 'Core', is_custom: false },
  { id: 'bicycle-crunches', name: 'Bicycle Crunches', category: 'Core', is_custom: false },
  { id: 'leg-raises', name: 'Leg Raises', category: 'Core', is_custom: false },
  { id: 'hanging-leg-raises', name: 'Hanging Leg Raises', category: 'Core', is_custom: false },
  { id: 'ab-wheel-rollouts', name: 'Ab Wheel Rollouts', category: 'Core', is_custom: false },
  { id: 'dead-bug', name: 'Dead Bug', category: 'Core', is_custom: false },
  { id: 'bird-dog', name: 'Bird Dog', category: 'Core', is_custom: false },

  // Cardio
  { id: 'running', name: 'Running', category: 'Cardio', is_custom: false },
  { id: 'cycling', name: 'Cycling', category: 'Cardio', is_custom: false },
  { id: 'swimming', name: 'Swimming', category: 'Cardio', is_custom: false },
  { id: 'rowing', name: 'Rowing', category: 'Cardio', is_custom: false },
  { id: 'elliptical', name: 'Elliptical', category: 'Cardio', is_custom: false },
  { id: 'jumping-jacks', name: 'Jumping Jacks', category: 'Cardio', is_custom: false },
  { id: 'burpees', name: 'Burpees', category: 'Cardio', is_custom: false },
  { id: 'high-knees', name: 'High Knees', category: 'Cardio', is_custom: false },
  { id: 'jump-rope', name: 'Jump Rope', category: 'Cardio', is_custom: false },
  { id: 'treadmill', name: 'Treadmill', category: 'Cardio', is_custom: false },

  // Full Body
  { id: 'thrusters', name: 'Thrusters', category: 'Full Body', is_custom: false },
  { id: 'burpees', name: 'Burpees', category: 'Full Body', is_custom: false },
  { id: 'kettlebell-swings', name: 'Kettlebell Swings', category: 'Full Body', is_custom: false },
  { id: 'clean-and-press', name: 'Clean and Press', category: 'Full Body', is_custom: false },
  { id: 'man-makers', name: 'Man Makers', category: 'Full Body', is_custom: false },
  { id: 'bear-crawls', name: 'Bear Crawls', category: 'Full Body', is_custom: false },
  { id: 'crab-walks', name: 'Crab Walks', category: 'Full Body', is_custom: false },
  { id: 'turkish-get-ups', name: 'Turkish Get-ups', category: 'Full Body', is_custom: false },
];
